sudo: false
language: perl
perl:
  - '5.10' # centos.6
  - '5.16' # centos 7
  - '5.24' # debian 9
  - '5.26' # ubuntu 18.04
matrix:
  allow_failures:
    - perl: '5.26'
    - perl: '5.24'
addons:
  apt:
    packages:
      - tar
      - patch
      - gcc
      - perl
      - libmysqlclient-dev
      - make
install: true
before_script:
 - pushd cpan-mirror/authors/id/D/DO/DORMANDO
 - gunzip -c MogileFS-Server-2.73.tar.gz | tar --delete MogileFS-Server-2.73/t/mogstored-shutdown.t | gzip -c - > MogileFS-Server-2.73.tar.gz.new
 - mv MogileFS-Server-2.73.tar.gz.new MogileFS-Server-2.73.tar.gz
 - popd
script:
  - ./cpanm -L extlib --mirror=$(pwd)/cpan-mirror/ --mirror-only --installdeps --test-only .
